# Generated by Django 5.0.4 on 2024-04-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('normal_price', models.IntegerField()),
                ('sale_price', models.IntegerField(blank=True)),
                ('count', models.IntegerField()),
                ('character', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=150)),
            ],
        ),
    ]
