# Generated by Django 5.0.4 on 2024-06-26 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_product_battery_product_memory_product_op_memory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sale_price',
            new_name='discounted_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='battery',
            new_name='product_details',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='character',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='count',
            new_name='regular_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='normal_price',
            new_name='stock_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='memory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='op_memory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='proc',
        ),
    ]
