# Generated by Django 5.0.4 on 2024-06-26 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0003_rename_sale_price_product_discounted_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='goods',
        ),
    ]
