# Generated by Django 5.0.4 on 2024-09-01 09:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0007_cart_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(max_length=150, null=True, verbose_name='категория')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='sub_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_subcategory', models.CharField(max_length=150, null=True, verbose_name='подкатегория')),
            ],
            options={
                'verbose_name': 'подкатегория',
                'verbose_name_plural': 'подкатегории',
            },
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.AddField(
            model_name='goods',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goods',
            name='discounted_price',
            field=models.IntegerField(blank=True, verbose_name='скидочная цена'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='product_details',
            field=models.CharField(blank=True, max_length=150, verbose_name='описание продукта'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='product_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='название продукта'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='regular_price',
            field=models.IntegerField(verbose_name='обычная цена'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='stock_quantity',
            field=models.IntegerField(verbose_name='количество товара'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.OneToOneField(null=True, on_delete=models.SET('Прочие'), to='magazine.category'),
        ),
        migrations.AddField(
            model_name='goods',
            name='sub_category',
            field=models.OneToOneField(null=True, on_delete=models.SET('Прочие'), to='magazine.sub_category'),
        ),
    ]
