# Generated by Django 5.0.4 on 2024-09-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0008_category_sub_category_alter_goods_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_category',
            name='product_category',
            field=models.OneToOneField(null=True, on_delete=models.SET('Прочие'), to='magazine.category'),
        ),
    ]
