# Generated by Django 5.0.4 on 2024-09-02 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0009_sub_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='magazine.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='magazine.sub_category', verbose_name='подкатегория'),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='product_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='magazine.category', verbose_name='Категория'),
        ),
    ]
