# Generated by Django 5.0.4 on 2024-09-04 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0010_alter_goods_category_alter_goods_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150, null=True, verbose_name='категория')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.RemoveField(
            model_name='sub_category',
            name='product_category',
        ),
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='magazine.product_category', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='product_subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=150, null=True, verbose_name='подкатегория')),
                ('category_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='magazine.product_category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'подкатегория',
                'verbose_name_plural': 'подкатегории',
            },
        ),
        migrations.AlterField(
            model_name='goods',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='magazine.product_subcategory', verbose_name='подкатегория'),
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='sub_category',
        ),
    ]
