# Generated by Django 5.0.4 on 2024-09-23 19:10

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0011_product_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_category',
            options={'managed': True, 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='product_subcategory',
            options={'managed': True, 'verbose_name': 'подкатегория', 'verbose_name_plural': 'подкатегории'},
        ),
        migrations.AddField(
            model_name='goods',
            name='product_image',
            field=models.FileField(default=django.utils.timezone.now, max_length=255, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])]),
            preserve_default=False,
        ),
    ]
