# Generated by Django 5.0.4 on 2024-09-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0014_product_image_delete_imageupload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='product_details',
            field=models.CharField(blank=True, verbose_name='описание продукта'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='product_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='название продукта'),
        ),
    ]
