# Generated by Django 5.0.4 on 2024-09-28 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0016_alter_cart_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='product_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='product_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='название продукта'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='magazine.product_category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='product_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='название продукта'),
        ),
    ]
